name: Build and Deploy Code

on: [push, pull_request]

jobs:
  job1:
    run-on: window
    steps:
      - name: pulling github repo
        uses: actions/checkout@v2
      - name: say hi
        run: echo "Hello World"  

# on: [push, pull_request]
#   push:
#     branches:
#       - "main"
#       - "another branch"
#   pull_request:
#     branches:
#       - "any branch"
